version: "3.8"
services:
  domaininja:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domaininja_container
    env_file:
      - .env
    volumes:
      - domaininja_data:/domaininja
    restart: always

volumes:
  domaininja_data:
