USE ninja;

CREATE TABLE IF NOT EXISTS domains (
    domain_id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    domain VARCHAR(1000) NOT NULL,
    first_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    times_seen INT(8) NOT NULL DEFAULT 1
);


